pipeline{
    agent any
    
    stages{
        stage ('Check stage'){
            steps{
            withMaven(maven : 'Maven'){
                   bat 'mvn --version'
            }
        }
    }
        
    stage('Compile stage'){
            steps {
                withMaven(maven : 'Maven'){
                bat 'mvn -f mvm-math/pom.xml compile'
            }
        }
    }
        stage('Test stage'){
            steps {
            withMaven(maven : 'Maven'){
                 bat 'mvn -f mvm-math/pom.xml install'            
                 }
        }
    }
}        
}