pipeline{

	agent any
	try{
	stages{ 
	
	
		stage('Check stage')
		     {
		  				steps{
		    					bat 'Maven --version'
		                      }
		       } 
		
		stage('Compile stage')
		{
		     steps{
		         withMaven(){
		             bat 'Maven -f mvn-math/pom.xml compile'
		         }

		         
		         }
		         
		    }
		       
		       stage('test stage')
		       	{
		       			steps
		       				{
		       				withMaven(maven:'Maven')
		       				{
		       				  bat 'Maven -f mvn-math/pom.xml install'
		       				}
    

		       	 					
		       				}
		       	}
		       
		       
		       
		       }
		       
		     }
		     finally
		     {
		     
		     }  
		       
		       }